;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #434955
background-alt = #373b41
foreground = #92c5d0
primary = #a89ce8
secondary = #8abeb7
alert = #a54242
disabled = #707880
separator = #acc5d5

[global/wm]
include-file = $HOME/.config/polybar/modules.ini

[bar/bar]
width = 100%
height = 24pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-bottom-size = 2pt
border-bottom-color = #666ca1

padding-left = 0
padding-right = 2

module-margin = 1

separator = |
separator-foreground = ${colors.separator}

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=13;3
font-1 = JetBrainsMono Nerd Font:size=18;5
font-2 = Material Design Icons:style=Bold:size=13;3
font-3 = unifont:fontformat=truetype:size=13:antialias=true;

modules-left = xworkspaces
modules-center = xwindow
modules-right = pulseaudio xkeyboard memory cpu date eth powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

monitor = DP-0
[settings]
screenchange-reload = true
pseudo-transparency = true
wm-restack = bspwm
